version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3011:3011"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - PORT=3011
